name: build

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with: 
          cache: 'npm'
  
      - name: Install dependencies
        run: npm install
  
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
  
      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}

      - name: Stop current PM2 process by name
        run: pm2 stop nestjs-app || true

      - name: Build app
        run: npm run build
      
      - name: Start new PM2 process with name
        run: pm2 start "npm run start:prod" --name nestjs-app
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
          S3_ENDPOINT: ${{secrets.S3_ENDPOINT}}
          S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
          JWT_EXP: ${{env.JWT_EXP}}
          PORT: ${{env.PORT}}
          S3_REGION: ${{env.S3_REGION}}

      - name: Save PM2 process list
        run: pm2 save
