name: build

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with: 
          cache: 'npm'
  
      - name: Install dependencies
        run: npm install
  
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
  
      - name: Generate Prisma client
        run: npx prisma generate
  
      - name: Restart PM2 process
        run: pm2 restart ales-nest
